name: Deploy to s3
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
      - uses: actions/checkout@main
      - name: Build project files
        run: |
          npm ci
          npm run build-staging
        env:
          VUE_APP_PAT: ${{ secrets.VUE_APP_PAT }}
      - name: Deploy to s3
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-east-1
        run: |
          aws s3 cp dist s3://philagov-vue-apps/embedded/covid-guidance/staging/ --recursive # change it
          